# 主机和端口
HOST = "0.0.0.0"
PORT = 4040
# 最大连结数
MAX_CONNECTION = 100
# 视频路径
VIDEO_DIR = "/videos/"
# 最大上传大小(MB)
MAX_UPLOADSIZE = 500
# 数据库DSN
MYSQL_DSN = "root:Xr111900@tcp(rm-wz9p9wn6719qplwioho.mysql.rds.aliyuncs.com:3306)/streaming?charset=utf8"